### PR TITLE
Refactored as a directive 

### PR DESCRIPTION
**Pull request by ThomasPe**
Finally, I got around to dealing with the rebase. Hopefully I've done it right this time - the GitHub Desktop app is really helpful, though.

I have now refactored the builder controller so it can be used as a directive.
I feel it's now at a point where we can start working on it "issues-based" to weed out bugs and add missing features.

### CODE REVIEW

**Comment by nicklasb** [comment]
Cool, I will have a look tomorrow!

**Comment by nicklasb** [comment]
So, my problem is still that while yes, it is now a directive, the application that housed the functionality is gone. The application was first and foremost actually sort of usable, and second, it made it easy to play around and test the functionality. 

It is likely that we should more clearly split those two in some future, but at this stage at least I want the application to remain somewhere in the repository, perhaps as an example or utility, but one that uses the directive. Because as it is now, the sfbSchema isn't really separate anyway, it is in the app structure.

I would propose a build/lib for the directive and its dependencies, and a build/example or build/utility for the.
Do you agree with that? If so I am for merging this to the directive branch now and then continue with re-adding the application. 

@rowino : However, you were considering some rewriting, was that WRT the app or the functionality in the directive, the actual builder?

**Comment by ThomasPe** [comment]
Sure, that sounds good. 
However there's currently one issue - the app is currently storing the form & schema info in one combined file and only splits this into seperate schema and form markup files on export. So with the directive you currently can't edit existing forms.
It certainly would be great to hear @rowino 's thoughts on how to proceed.

**Comment by rowino** [comment]
@ThomasPe, first thanks for the input. Nice having others contribute into it. As for the directive, I had mentioned to @nicklasb earlier that I was thinking of spliting the generator into a plain js library then create a angular-directive separate. Reason being to allow reuse with other frameworks. We'll then have a site somewhere for people to use it for quick forms while for in-app use one can use the directive or their framework of choice. Does this shade some light?

**Comment by nicklasb** [comment]
@rowino, @ThomasPe : 
That would obviously be great, an ES6 library would make it portable on all web frontends, much as we do now with ASF itself.

Basically that would mean that this repo would become home to the pure ES6 library, and then we would create another for the angular/react/whatever directives/implementations.

The plan for the json-schema-core has been to later call it json-schema-core-es6, as there are other core implementations on the horizon, like json-schema-core-java, json-schema-core-php and whatnot.

Should we therefore rename this repo json-schema-form-builder-es6?
And then implement the directives in angular-schema-form-builder repos and so on?

And then the app, wherever that ends up will be what it wants to be?

**Comment by nicklasb** [comment]
Either way, that means that we just merge this and works from there?

**Comment by ThomasPe** [comment]
sounds good @rowino & @nicklasb

**Comment by nicklasb** [comment]
Done.

**Pull request merged**
